# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pageLoader

on:
  push:
    branches: [ master ]

jobs:
  main_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: npm run test-publish
      env:
        CI: true
        CC_TEST_REPORTER_ID: ${{secrets.codeClimate}}
    - name: coverage
      uses: paambaati/codeclimate-action@v2.5.5
      with:
        coverageCommand: npm run test --coverage --watchAll=false
        coverageLocations:
          "${{github.workspace}}/test-coverage/lcov.info:lcov"
    - name: publish
      uses: primer/publish@master
      env:
        NPM_AUTH_TOKEN: ${{secrets.npm}}
        args: '--dry-run'
