# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pageLoader

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
    - run: npm run build
    - run: npm run test-publish
      env:
        CI: true

  coverage:
    needs: [ test ]
    strategy:
      matrix:
        node-version: [13.x]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - uses: paambaati/codeclimate-action@v2.5.5
      env:
        CC_TEST_REPORTER_ID: ${{secrets.codeClimate}}
      with:
        coverageCommand: npm run test --coverage --watchAll=false
        coverageLocations:
          "${{github.workspace}}/test-coverage/lcov.info:lcov"
  

  publish:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 13
          registry-url: https://registry.npmjs.org/
      - name: build package
        - run: npm ci
        - run: npm run build
      - name: Register Token
        run: |
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > /home/runner/work/_temp/.npmrc
          echo "_auth=$NODE_AUTH_TOKEN" >>  /home/runner/work/_temp/.npmrc
          echo "email=<rehemtoha@gmail.com>" >>  /home/runner/work/_temp/.npmrc
          echo "always-auth=true" >>  /home/runner/work/_temp/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm}}
      - name: Publish stable
        run: npm publish
